nic-info helper: loop on every card if invoked w/o arguments. Refs #3041

diff --git a/root/usr/libexec/nethserver/nic-info b/root/usr/libexec/nethserver/nic-info
--- a/root/usr/libexec/nethserver/nic-info
+++ b/root/usr/libexec/nethserver/nic-info
@@ -1,23 +1,68 @@
-#!/bin/sh
+#!/bin/bash
 
-card=$1
-if [ "x$card" == "x" ]; then
-    exit 1
+#
+# Copyright (C) 2015 Nethesis S.r.l.
+# http://www.nethesis.it - nethserver@nethesis.it
+#
+# This script is part of NethServer.
+#
+# NethServer is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License,
+# or any later version.
+#
+# NethServer is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with NethServer.  If not, see COPYING.
+#
+
+if [ "x${1}" == "x" ]; then
+    cards=($(ls -A -1 /sys/class/net))
+else
+    cards=($1)
 fi
 
-#Check if this is an Ethernet device (type=1)
-if [ `cat /sys/class/net/$card/type` == "1" ]; then
-	hwaddr=`cat /sys/class/net/$card/address`
+for card in ${cards[@]}; do
 
-	#Check that is no VLAN if
-	if [[ ! "$card" =~ "[.]" ]]; then
+    hwaddr=
+    type=
+    model=
+    driver=
+    speed=
+    link=
 
-                # Check if this not a bridge or a tun/tap
-                if [ ! -e /sys/class/net/$card/brforward ] && [ ! -e /sys/class/net/$card/tun_flags ]; then
+    # Error on non-existing devices
+    if ! [ -e "/sys/class/net/${card}" ]; then
+	echo "[ERROR] nic-info: interface ${card} does not exist" 1>&2
+	exit 1
+    fi
+    
+    # Skip non-Ethernet physical devices (type=1)
+    if [ `cat /sys/class/net/${card}/type` != "1" ]; then
+       continue
+    fi
 
-			#Check if mac is valid (not 00:00... or FF:FF...)
-			if [ ! "$hwaddr" == "00:00:00:00:00:00" ];then
-				if [ ! "$hwaddr" == "ff:ff:ff:ff:ff:ff" ];then
+    # Skip VLANs
+    if [[ "${card}" =~ "[.]" ]]; then
+	continue
+    fi
+
+    # Skip bridge and tun/tap
+    if [ -e /sys/class/net/${card}/brforward ] || [ -e /sys/class/net/${card}/tun_flags ]; then
+        continue
+    fi
+
+    hwaddr=`cat /sys/class/net/${card}/address`
+	
+    # Skip if mac is not valid (00:00... or FF:FF...)
+    if [ "${hwaddr}" == "00:00:00:00:00:00" ] || [ "${hwaddr}" == "ff:ff:ff:ff:ff:ff" ]; then
+	continue
+    fi
+	
 					driver=`basename $(ls -l /sys/class/net/$card/device/driver | awk '{print$NF}' )`
 					type=`basename $(ls -l /sys/class/net/$card/device/subsystem | awk '{print$NF}' )`
 
@@ -48,11 +93,8 @@ if [ `cat /sys/class/net/$card/type` == "1" ]; then
 					speed=`cat /sys/class/net/$card/speed 2>/dev/null`
 					link=`cat /sys/class/net/$card/carrier 2>/dev/null`
 
-				fi
-			fi
-		fi
-	fi
-fi
-		echo $card,$hwaddr,$type,$model,$driver,$speed,$link
 
-exit 0
+    echo $card,${hwaddr//,/ },${type//,/ },${model//,/ },${driver//,/ },$speed,$link
+
+done
+
