Synchronize admin/root passwords. Refs #2492
If AdminIsNotRoot is disabled, admin and root passwords are the same.

Refactored the bash script, removing reduntant nested IFs.

diff --git a/root/etc/e-smith/events/actions/password-set b/root/etc/e-smith/events/actions/password-set
--- a/root/etc/e-smith/events/actions/password-set
+++ b/root/etc/e-smith/events/actions/password-set
@@ -20,25 +20,36 @@
 # along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-if [ $# -ge 3 ]; then
-   EVENT=$1
-   USER=$2
-   FILE=$3
-   echo "Change password for user $USER from $FILE"
-   if [ -f $FILE ]; then
-     PASSWORD=`cat $FILE`
-     echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin $USER
-     if [ "$USER" == "admin" ]; then
-         AdminIsNotRoot=$(/sbin/e-smith/config get AdminIsNotRoot)
-         if [ "$AdminIsNotRoot" != "enabled" ]; then # keep admin and root password in sync
-             echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin root
-         fi
-     fi
-   else
-     echo "Password file not found"
-     exit 1
-   fi
-else
-   echo "Not enough arguments"
-   exit 1
+if ! [ $# -ge 3 ]; then
+   echo "[ERROR] Not enough arguments."
+   exit 2
 fi
+
+EVENT=$1
+USER=$2
+FILE=$3
+
+if ! [ -f "${FILE}" ]; then
+    echo "[ERROR] Password file not found"
+    exit 1
+fi
+
+PASSWORD=`cat $FILE`
+echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin $USER
+
+if [ "$USER" == "admin" ]; then
+    other="root"
+elif [ "$USER" == "root" ]; then
+    other="admin"
+else
+    other=""
+fi
+
+if [ -n "${other}" ] && /usr/bin/getent passwd "${other}" &>/dev/null; then
+    AdminIsNotRoot=$(/sbin/e-smith/config get AdminIsNotRoot)
+    if [ "$AdminIsNotRoot" != "enabled" ]; then 
+	# Synchronize password with "other" account (see #2492.9)
+        echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin "${other}"
+    fi
+fi
+
